name: SimpleModeration
version: '${version}'
main: com.beanbeanjuice.simplemoderation.SimpleModeration
api-version: '1.13'
load: STARTUP
authors: [ beanbeanjuice ]
softdepend:
  - PlaceholderAPI
description: A Minecraft punishment plugin.
website: https://www.github.com/beanbeanjuice/SimpleModeration
folia-supported: true

commands:
  ping:
    description: Confirm the punishment plugin is working!
    usage: /<command>
    permission: simplemoderation.ping
    aliases:
      - punishmentping
  freeze:
    description: Freeze a player.
    permission: simplemoderation.freeze
  unfreeze:
    description: Unfreeze a player.
    permission: simplemoderation.unfreeze
